
spring:
  datasource:
    url: jdbc:sqlserver://rayudu1.database.windows.net:1433;database=productdb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: rayudu
    password: Uppu@2920
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect
server:
  port: 9191


