
spring:
  datasource:
    url: jdbc:sqlserver://swetha.database.windows.net:1433;database=database1;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: swetha
    password: rootroot@1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect
server:
  port: 9191


